### ISSUE TITLE
Implement simulation support

### ISSUE THREAD

**Issue by banool** [aptos-labs/Aptos-Unity-SDK#62]

**Comment by kPatch** [comment]
In `develop` branch now, from `add_tokenclient`

**Comment by kPatch** [comment]
Added in last release https://github.com/aptos-labs/Aptos-Unity-SDK/blob/471925257d38180e79ff99292718958e4c8c4a7e/Assets/Aptos-Unity-SDK/Code/Aptos.Unity.Rest/RestClient.cs#L755
